kind: pipeline
type: docker
name: release-linux-amd64

platform:
  arch: amd64
  os: linux

trigger:
  event:
  - tag

steps:
- name: build
  image: ar0660/angular:18
  commands:
  - npm install
  - ng build

- name: publish
  image: plugins/docker
  settings:
    dockerfile: build/Dockerfile.linux.amd64
    repo: flarexio/app
    auto_tag: true
    auto_tag_suffix: linux-amd64
    username:
      from_secret: REGISTRY_USERNAME
    password: 
      from_secret: REGISTRY_PASSWORD

---
kind: pipeline
type: docker
name: release-manifest

platform:
  arch: amd64
  os: linux

trigger:
  event:
  - tag

steps:
- name: publish
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    spec: build/manifest.txt
    username:
      from_secret: REGISTRY_USERNAME
    password: 
      from_secret: REGISTRY_PASSWORD

depends_on:
  - release-linux-amd64
